name: carbon-aware-data-store
version: '3.8'
services:
  api:
    build:
      context: api_data
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  
  go_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"